### ISSUE TITLE
(4228) User still can set current as expiry date in two screen. One is edit notification and another is add notification from edit class.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#1]
(4228) User still can set current as expiry date in two screen. One is edit notification and another is add notification from edit class.

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please check.
Cause- Inadequate Checklist

**Comment by rahul-kumar11** [comment]
retested and passsed
