### ISSUE TITLE
Org admin  can not create a user with a space now but if a user is created by org admin and user is not completed partial registration and now org admin edit that user and change username with a space. System will update user details without an error. Now user is not able to login in the system.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#11]
Org admin  can not create a user with a space now but if a user is created by org admin and user is not completed partial registration and now org admin edit that user and change username with a space. System will update user details without an error. Now user is not able to login in the system.

**Comment by jainsmriti** [comment]
Fixed. (Inadequate Checklist )

**Comment by rahul-kumar11** [comment]
retested and passed
