### ISSUE TITLE
If org admin try to create a user with a username then he should not get the "Email sign in details " check box should not be displayed. But if org admin put the existing username then the error comes and "Email sign in details " check box displayed. although the username check box is checked.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#12]
If org admin try to create a user with a username then he should not get the "Email sign in details " check box should not be displayed. But if org admin put the existing username then the error comes and "Email sign in details " check box displayed. although the username check box is checked.

**Comment by jainsmriti** [comment]
Fixed (Inadequate Checklist).

**Comment by rahul-kumar11** [comment]
When user click on check box for "Email sign in details " and then click on "user name "check box " then the check box is hide but if the user again uncheck check box the "Email sign in details " check box is checked. This is incorrect.

**Comment by jainsmriti** [comment]
Fixed. Please re-check.

**Comment by rahul-kumar11** [comment]
retested and passed
