### ISSUE TITLE
If Cs admin send the notification by selecting "all teacher" option then notification is not received by the teacher only.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#14]
If Cs admin send the notification by selecting "all teacher" option then notification is not received by the teacher only.

I all other case notification is received perfectly.

**Comment by ankit-sanghvi** [comment]
Fixed.
Cause: Inapplicable/Inappropriate Method/Process

**Comment by rahul-kumar11** [comment]
retested and passed
