### ISSUE TITLE
If a user has activate a course in self study then he did not get the success  pop up on my course screen.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#15]
If a user has activate a course in self study then he did not get the success  pop up on my course screen.

**Comment by JB-PATEL** [comment]
can not re-produce this on Dev.

**Comment by rahul-kumar11** [comment]
Can you please have a look why pop up is not appearing in QA.

**Comment by JB-PATEL** [comment]
Rahul,

We has similar issue in rel 17 too. Please check this in UAT.  This is working as expected on different dev machines.

**Comment by rahul-kumar11** [comment]
I will check in UAT then I will close the issue.

**Comment by rahul-kumar11** [comment]
checked in Uat passed
