### ISSUE TITLE
If a user has activate a course in self study and now user join a class that has a course that is activated by user then user will get "user content with" pop up. If user click on "Yes"  on the pop up then user gets the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#16]
If a user has activate a course in self study and now user join a class that has a course that is activated by user then user will get "user content with" pop up. If user click on "Yes"  on the pop up then user gets the exception.

![3](https://cloud.githubusercontent.com/assets/7794513/10390401/0b2cba36-6e96-11e5-8af2-9e9cdfcbdaf7.png)

**Comment by ankit-sanghvi** [comment]
Can't Reproduce the same.

**Comment by rahul-kumar11** [comment]
reproduced  by @jainsmriti so assigning to her

**Comment by jainsmriti** [comment]
Unable to reproduce it. Please let me know if you face this issue again.

**Comment by rahul-kumar11** [comment]
Not able to reproduce.
