### ISSUE TITLE
Replace string not getting replace in Course Expiry for Teacher

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/TestRel17.2#20]
Replace string not getting replace in Course Expiry for Teacher

![replacestring issue](https://cloud.githubusercontent.com/assets/12691744/10430915/730a42b4-711f-11e5-8a9b-06a69e069973.PNG)

**Comment by dharamveerSanodiya** [comment]
Bug resolved. Please check.
Cause: Inadequate checklist

**Comment by jainsmriti** [comment]
![editdetails replacestring](https://cloud.githubusercontent.com/assets/12691744/10448965/17c6328e-71ae-11e5-9506-267283263c58.PNG)

**Comment by jainsmriti** [comment]
Please look into the Edit User Template.

**Comment by dharamveerSanodiya** [comment]
Bug is resolved. Please validate. 
Cause: Inherited defect.

**Comment by jainsmriti** [comment]
![course expiry for teacher](https://cloud.githubusercontent.com/assets/12691744/10510309/ca0121d2-734f-11e5-917d-6a3a1f63f467.PNG)


The replacement string is getting replaced in body part but not in Subject. Please look into it again.

**Comment by jainsmriti** [comment]
This is the notification for Course expiry for teacher.

**Comment by jainsmriti** [comment]
![course expiry](https://cloud.githubusercontent.com/assets/12691744/10511833/b4fde464-7359-11e5-8423-b6d3cb584581.PNG)

Notification for Course Expiry.

**Comment by dharamveerSanodiya** [comment]
Course expiry for teacher - done 
Course Expiry - done 
Cause - Inherited defects

**Comment by jainsmriti** [comment]
Not working yet. Please recheck.

**Comment by dharamveerSanodiya** [comment]
I guess, It should work now.

**Comment by jainsmriti** [comment]
![course expired](https://cloud.githubusercontent.com/assets/12691744/10535231/97971f9e-73fe-11e5-9fbd-47c0282adab5.PNG)

Course Expired Notification. Please check.

**Comment by dharamveerSanodiya** [comment]
Done. Please validate

**Comment by rahul-kumar11** [comment]
Tested and Passed.
