### ISSUE TITLE
The generic  error message displayed on my info page when details is not updated in EAC and LMS is displayed in green colour. The error message should be displayed in red colour.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#22]
The generic  error message displayed on my info page when details is not updated in EAC and LMS is displayed in green colour. The error message should be displayed in red colour.

**Comment by dharamveerSanodiya** [comment]
Suggestion is implemented. Please check.
Cause: Suggestion

**Comment by rahul-kumar11** [comment]
retested and passed
