### ISSUE TITLE
For Start your course Without teacher notification no replace string are visible in 'View replacement string popup'

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/TestRel17.2#25]
For Start your course Without teacher notification no replace string are visible in 'View replacement string popup'

**Comment by dharamveerSanodiya** [comment]
Query is check in for this, Please check again with updated QA. 
Hope should work as expected.
Cause: Existing bug

**Comment by jainsmriti** [comment]
Tested and Passed.
