### ISSUE TITLE
JQuery 1.5.1 and 1.7.1 Potential Cross Site Scripting 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#29]
(https://oxfordlearn.mantishub.com/view.php?id=3858)

Please try this script in "<b onmouseover=alert('Wufff!')>click me!</b>" in  add message.

**Comment by rahul-kumar11** [comment]
<META HTTP-EQUIV="refresh"
CONTENT="0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgndGVzdDMnKTwvc2NyaXB0Pg">

**Comment by JB-PATEL** [comment]
HTML event and meta tag handled. Please re-test

**Comment by rahul-kumar11** [comment]
retested and passed
