### ISSUE TITLE
If a teacher enters an access code for a student from edit course screen and then student try to launch the course, student get the terms and condition pop up. If student  click the check box and click on continue then  user gets the exception.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#3]
If a teacher enters an access code for a student from edit course screen and then student try to launch the course, student get the terms and condition pop up. If student  click the check box and click on continue then  user gets the exception.
![1](https://cloud.githubusercontent.com/assets/7794513/10303685/1029bb34-6c33-11e5-9a4b-cff4478802dc.jpg)

**Comment by ankit-sanghvi** [comment]
Cause : Inherited Defects

**Comment by rahul-kumar11** [comment]
retested and passed
