### ISSUE TITLE
Auto fill password off not working in Create new User for CS admin

### ISSUE THREAD

**Issue by jainsmriti** [subrata1106/TestRel17.2#37]
![autofill password](https://cloud.githubusercontent.com/assets/12691744/10542225/57b7c780-7434-11e5-8382-6a40e3168387.PNG)

**Comment by JB-PATEL** [comment]
Fixed. Pls check.
Cause : Inadequate Self Reviews

**Comment by jainsmriti** [comment]
Checked and passed.
