### ISSUE TITLE
Some of the notification is not displayed  sorted according to date.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#9]
Some of the notification is not displayed  sorted according to date.

![2](https://cloud.githubusercontent.com/assets/7794513/10332551/9f87d374-6cfb-11e5-9ba3-15899213208b.PNG)

**Comment by ankit-sanghvi** [comment]
Cause : Inherited Defect

**Comment by rahul-kumar11** [comment]
retested and passed
